#!/usr/bin/env bash

# dwm-startup (/usr/bin/dwm-startup)

# Set `feh` to change the wallpaper
source $HOME/.fehbg

# Set `unclutter` to hide the cursor after a second of inactivity
unclutter -root -idle 1 &

# Start `dwm` with a modified status bar
while true; do
  xsetroot -name "Db: $(dropbox status) | B: $(acpi -b | awk '{ print $4 $5 }' | sed 's/,/ \/ /g') | V: $(amixer get Master | grep 'Front Left:' | awk '{ print $5 }' | sed 's/\[\|\]//g') | $(date '+%d %b %Y') | $(date '+%H:%M')"
  sleep 10s
done & exec dwm
