#!/bin/sh

# dwm-startup (/usr/bin/dwm-startup)

# Start `dwm` with a modified status bar
while true; do
  xsetroot -name "Db: $(dropbox status) | W: $(iwconfig wlan0 | awk '/Link Quality/{ print $2 }' | sed 's/Quality=//') | B: $(acpi -b | awk '{ print $4 $5 }' | sed 's/,/ \/ /g') | V: $(amixer get PCM | awk '/Front Left:/{ print $5 }' | sed 's/\[\|\]//g') | $(date '+%d %b %Y') | $(date '+%H:%M')"
  sleep 10s
done & exec dwm
